(add-to-list 'default-frame-alist '(height . 72))
(add-to-list 'default-frame-alist '(width . 100))
;;(evil-mode 0)
(add-to-list 'auto-mode-alist '("\\.boot\\'" . clojure-mode))
(setq linum-format "%4d \u2502 ")
